### ISSUE TITLE
Fix host_certificate dir + rollback

### ISSUE THREAD

**Issue by ejr004** [simple-framework/simple_grid_puppet_module#101]
- create host_certificate/$host_fqdn
- set permissions 

Also, looks like pre_deploy rollback is not removing  host_certificates. That needs to be taken care of in this issue as well.

**Comment by maany** [comment]
We must also check how to copy the certs if permission set by site admin is already 600/400

**Comment by maany** [comment]
At present, the fileserver seems to be copying only certificates with permission 777.
We need to change the existing permissions on config master before copying certificates and change them back to sth more secure on the config master, after copying them

**Comment by maany** [comment]
Puppet only copies files owned by puppet:puppet or puppet:root with permissions 555
