### ISSUE TITLE
Check docker swarm overlay ip address crashes with ingress or other overlay networks

### ISSUE THREAD

**Issue by maany** [simple-framework/simple_grid_puppet_module#128]
https://docs.docker.com/network/overlay/#customize-the-default-ingress-network

Ingress is randomly chosen

**Comment by ejr004** [comment]
- docker swarm init on ce02
- 
- docker network rm ingress
- 
- docker network create simple --driver overlay --attachable --subnet 10.0.0.0/16
- 
- On puppet master
- 
- create /etc/simple_grid/.swarm_status
- 
- and add tokens from ce02 for worker and manager
- 
- then run pre_deploy

**Comment by maany** [comment]
Issue solved in #119
